Ana/add message for polkadot treasuries
luniehq/lunie pull request #4955
Opened 2020-09-21 14:33 UTC by Bitcoinera

Closes #ISSUE

**Description:**

Adds this message to Polkado Treasury proposals:

![image](https://user-images.githubusercontent.com/40721795/93780267-3b2e4180-fc28-11ea-98f3-4f1a457cc80b.png)

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

2020-09-21 14:36 UTC, faboweb commented
<!-- NETLIFY DEPLOY COMMENT GENERATED BY ACTIONS_NETLIFY -->
🚀 Deployed on https://5f68ba726a02431af7b7250f--lunieio.netlify.app

2020-09-21 14:38 UTC, jbibla commented
this is not the right way to do this - if we want to include the message should alter the summary. the problem is that the summary is being displayed as a param change proposal - not a `type: treasury`

2020-09-21 14:39 UTC, jbibla requested changes
not important right now and not the right implementation

2020-09-21 15:07 UTC, Bitcoinera commented
> this is not the right way to do this - if we want to include the message should alter the summary. the problem is that the summary is being displayed as a param change proposal - not a `type: treasury`

No, the problem is that we would need a network specific message for Polkadot networks, since we don't know how other Treasury proposals in other networks will look like. Council only exists in Polkadot networks

2020-09-21 18:16 UTC, jbibla commented
true. so in the API we can change the summary message based on whether or not it's a polkadot network.

2020-09-22 12:05 UTC, Bitcoinera commented
> true. so in the API we can change the summary message based on whether or not it's a polkadot network. but we shouldn't use a bar for this.

Done!

2020-09-22 12:10 UTC, Bitcoinera commented
Debugging this:

![image](https://user-images.githubusercontent.com/40721795/93880178-54dd9080-fcdd-11ea-9d85-83c49c89b6c8.png)

2020-09-22 20:38 UTC, jbibla commented on api/lib/reducers/polkadotV0-reducers.js
> +      `\nTreasury proposals in ${network.title} can only be voted by the council members.`,
```suggestion
      `\nTreasury proposals on ${network.title} can only be voted on by council members.`,
```

2020-09-22 20:40 UTC, jbibla approved these changes

2020-09-22 20:42 UTC, merged

2020-09-23 09:41 UTC, Bitcoinera commented on api/lib/reducers/polkadotV0-reducers.js
> +      `\nTreasury proposals in ${network.title} can only be voted by the council members.`,
Native speaker powah!