Ana/5190 extension banner about sunsetting
luniehq/lunie pull request #5192
Opened 2020-11-09 10:26 UTC by Bitcoinera

Closes #5190

**Description:**

![image](https://user-images.githubusercontent.com/40721795/98529607-1ea0a400-227e-11eb-8584-189586f8f18c.png)

![image](https://user-images.githubusercontent.com/40721795/98529551-09c41080-227e-11eb-9e81-59f547761c1e.png)

I tried to fix the Bar styles without removing `scoped` from `style scoped`, but I didn't find how to. Also, it doesn't make sense to have the closing 'x' in that particular banner (it reappears every time the user reopens the extension):

I think it makes more sense to create a new component from 0. It is just a simple banner. What do you think?

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

2020-11-09 22:04 UTC, jbibla commented on extension/src/components/SunsettingWarningBar.vue
> +    Lunie Extension will be soon sunset and won't receive further support. More
```suggestion
    We are sunsetting the Lunie Extension. Please read our announcement for more information.
```

2020-11-09 22:04 UTC, jbibla commented on extension/src/components/SunsettingWarningBar.vue
> +    infos
```suggestion

```

2020-11-09 22:05 UTC, jbibla commented
can you removed the 'x' from the bar?

2020-11-09 23:55 UTC, faboweb approved these changes

2020-11-09 23:57 UTC, faboweb requested changes
remove x

2020-11-10 09:21 UTC, Bitcoinera commented
> remove x

Done

2020-11-10 09:24 UTC, faboweb commented
<!-- NETLIFY DEPLOY COMMENT GENERATED BY ACTIONS_NETLIFY -->
🚀 Deployed on https://5faa5c481fb992735165b550--lunieio.netlify.app

2020-11-10 16:14 UTC, merged